/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    workspaces: Workspace;
    memberships: Membership;
    'repo-bindings': RepoBinding;
    'view-configs': ViewConfig;
    comments: Comment;
    approvals: Approval;
    notifications: Notification;
    favorites: Favorite;
    'audit-log': AuditLog;
    'ai-skills': AiSkill;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    workspaces: WorkspacesSelect<false> | WorkspacesSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'repo-bindings': RepoBindingsSelect<false> | RepoBindingsSelect<true>;
    'view-configs': ViewConfigsSelect<false> | ViewConfigsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    approvals: ApprovalsSelect<false> | ApprovalsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'ai-skills': AiSkillsSelect<false> | AiSkillsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'clone-workspace-repo': TaskCloneWorkspaceRepo;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Identyfikator użytkownika z Keycloak (claim „sub").
   */
  keycloakSub: string;
  email: string;
  name?: string | null;
  locale?: ('pl' | 'en' | 'de') | null;
  /**
   * Częstotliwość zbiorczych powiadomień e-mail o nieprzeczytanych zdarzeniach.
   */
  emailDigest?: ('none' | 'daily' | 'weekly') | null;
  lastDigestAt?: string | null;
  globalRoles?: 'system_admin'[] | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces".
 */
export interface Workspace {
  id: number;
  name: string;
  /**
   * Kod workspace (URL). Pozostaw puste — wygeneruje się z nazwy.
   */
  slug?: string | null;
  defaultView: 'direct' | 'client_business' | 'client_technical';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  workspace: number | Workspace;
  user: number | User;
  roles: ('workspace_maintainer' | 'editor' | 'client_technical' | 'client_business' | 'viewer')[];
  /**
   * Uprawnienia przyznane ponad domyślne wynikające z ról.
   */
  grantedPermissions?:
    | (
        | 'read'
        | 'comment'
        | 'approve'
        | 'edit-wysiwyg'
        | 'edit-raw'
        | 'page-create'
        | 'page-delete'
        | 'page-rename'
        | 'page-duplicate'
        | 'props-view'
        | 'props-edit'
        | 'history-view'
        | 'reports-view'
        | 'ai-use'
      )[]
    | null;
  /**
   * Uprawnienia odebrane mimo że wynikają z ról.
   */
  revokedPermissions?:
    | (
        | 'read'
        | 'comment'
        | 'approve'
        | 'edit-wysiwyg'
        | 'edit-raw'
        | 'page-create'
        | 'page-delete'
        | 'page-rename'
        | 'page-duplicate'
        | 'props-view'
        | 'props-edit'
        | 'history-view'
        | 'reports-view'
        | 'ai-use'
      )[]
    | null;
  /**
   * Jeśli ustawione, zastępuje widoki wynikające z ról. Widok bezpośredni i tak tylko dla ról dostawcy/admina.
   */
  viewAccess?: ('direct' | 'client_business' | 'client_technical')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repo-bindings".
 */
export interface RepoBinding {
  id: number;
  workspace: number | Workspace;
  host: 'gitlab' | 'github';
  repoUrl: string;
  branch: string;
  /**
   * Nazwa zmiennej środowiskowej z tokenem (np. GITLAB_TOKEN). Token NIE jest przechowywany w bazie.
   */
  credentialRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "view-configs".
 */
export interface ViewConfig {
  id: number;
  workspace: number | Workspace;
  /**
   * Bezpośredni bez reguł = pełny dostęp (najbardziej permisywny). Widoki klienckie bez reguł = nic (fail-closed).
   */
  view: 'direct' | 'client_business' | 'client_technical';
  includeGlobs?:
    | {
        glob: string;
        id?: string | null;
      }[]
    | null;
  excludeGlobs?:
    | {
        glob: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Gdy włączone, ten widok nie pokazuje katalogów zaczynających się od „_" (np. _input) ani plików, które mają taki katalog w ścieżce.
   */
  hideUnderscored?: boolean | null;
  /**
   * Gdy wyłączone (domyślnie dla wszystkich widoków), nagłówek metadanych dokumentu (author, content_hash, sha256, last_synced…) nie jest renderowany. Gdy włączone — metadane są pokazywane jako tabela.
   */
  showMetadata?: boolean | null;
  source: 'hybrid' | 'docsconfig' | 'osnova';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  workspace: number | Workspace;
  path: string;
  kind: 'inline' | 'document';
  quote?: string | null;
  prefix?: string | null;
  suffix?: string | null;
  contextHash?: string | null;
  revision?: string | null;
  body: string;
  parent?: (number | null) | Comment;
  status: 'open' | 'resolved';
  accepted?: boolean | null;
  reactions?:
    | {
        emoji: string;
        authorSub: string;
        id?: string | null;
      }[]
    | null;
  authorSub: string;
  authorName?: string | null;
  authorEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approvals".
 */
export interface Approval {
  id: number;
  workspace: number | Workspace;
  path: string;
  revision?: string | null;
  status: 'in_review' | 'approved' | 'rejected' | 'changes_requested';
  note?: string | null;
  authorSub: string;
  authorName?: string | null;
  authorEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  type: 'mention' | 'reply' | 'approval' | 'approval_approved' | 'approval_changes';
  workspace?: (number | null) | Workspace;
  view?: string | null;
  path?: string | null;
  commentId?: string | null;
  actorName?: string | null;
  actorEmail?: string | null;
  excerpt?: string | null;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user: number | User;
  workspace: number | Workspace;
  view?: string | null;
  path: string;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action:
    | 'access-denied'
    | 'document-opened'
    | 'commit-pushed'
    | 'comment-created'
    | 'file-created'
    | 'file-deleted'
    | 'file-renamed'
    | 'file-duplicated'
    | 'file-restored'
    | 'properties-changed';
  workspace?: (number | null) | Workspace;
  userId?: string | null;
  userEmail?: string | null;
  view?: string | null;
  path?: string | null;
  detail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-skills".
 */
export interface AiSkill {
  id: number;
  /**
   * Puste = globalny szablon (pula).
   */
  workspace?: (number | null) | Workspace;
  key: string;
  name: string;
  description?: string | null;
  category: 'apply' | 'refine';
  /**
   * Dodatkowa instrukcja dla modelu (tryb wcielania).
   */
  instruction: string;
  enabled?: boolean | null;
  /**
   * Pochodzi z domyślnej puli.
   */
  builtin?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'clone-workspace-repo';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'clone-workspace-repo') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'workspaces';
        value: number | Workspace;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'repo-bindings';
        value: number | RepoBinding;
      } | null)
    | ({
        relationTo: 'view-configs';
        value: number | ViewConfig;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'approvals';
        value: number | Approval;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'ai-skills';
        value: number | AiSkill;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  keycloakSub?: T;
  email?: T;
  name?: T;
  locale?: T;
  emailDigest?: T;
  lastDigestAt?: T;
  globalRoles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces_select".
 */
export interface WorkspacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  defaultView?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  workspace?: T;
  user?: T;
  roles?: T;
  grantedPermissions?: T;
  revokedPermissions?: T;
  viewAccess?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repo-bindings_select".
 */
export interface RepoBindingsSelect<T extends boolean = true> {
  workspace?: T;
  host?: T;
  repoUrl?: T;
  branch?: T;
  credentialRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "view-configs_select".
 */
export interface ViewConfigsSelect<T extends boolean = true> {
  workspace?: T;
  view?: T;
  includeGlobs?:
    | T
    | {
        glob?: T;
        id?: T;
      };
  excludeGlobs?:
    | T
    | {
        glob?: T;
        id?: T;
      };
  hideUnderscored?: T;
  showMetadata?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  workspace?: T;
  path?: T;
  kind?: T;
  quote?: T;
  prefix?: T;
  suffix?: T;
  contextHash?: T;
  revision?: T;
  body?: T;
  parent?: T;
  status?: T;
  accepted?: T;
  reactions?:
    | T
    | {
        emoji?: T;
        authorSub?: T;
        id?: T;
      };
  authorSub?: T;
  authorName?: T;
  authorEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approvals_select".
 */
export interface ApprovalsSelect<T extends boolean = true> {
  workspace?: T;
  path?: T;
  revision?: T;
  status?: T;
  note?: T;
  authorSub?: T;
  authorName?: T;
  authorEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  workspace?: T;
  view?: T;
  path?: T;
  commentId?: T;
  actorName?: T;
  actorEmail?: T;
  excerpt?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  workspace?: T;
  view?: T;
  path?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  workspace?: T;
  userId?: T;
  userEmail?: T;
  view?: T;
  path?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-skills_select".
 */
export interface AiSkillsSelect<T extends boolean = true> {
  workspace?: T;
  key?: T;
  name?: T;
  description?: T;
  category?: T;
  instruction?: T;
  enabled?: T;
  builtin?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskClone-workspace-repo".
 */
export interface TaskCloneWorkspaceRepo {
  input: {
    workspaceId: string;
  };
  output: {
    files?: number | null;
    revision?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}